App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [

    url(r'^homeblog/',views.homeBlog,name='homeblog'),
    url(r'^addblog/',views.addBlog,name='addblog'),
    url(r'^addcontent/',views.addContent,name='addcontent'),
    url(r'^homecontent/(.*)',views.homeContent,name='homecontent'),
    url(r'^index/',views.index,name='index'),
    url(r'^detail/(.*)',views.detail,name='detail'),
    url(r'^add/',views.add,name='add'),
]

Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('App.urls',namespace='blog')),
]

App/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    btitle = models.CharField(max_length=20)
    bname = models.CharField(max_length=20)
    bcount = models.IntegerField(default=0)



class Content(models.Model):
    ctitle = models.ForeignKey(Blog)
    cname = models.CharField(max_length=20)
    cinfo = models.CharField(max_length=200)



# -------------------------------------------------

class Author(models.Model):
    aname = models.CharField(max_length=15)
    aage = models.IntegerField(default=18)
    asex = models.BooleanField(default=0)

class Eassy(models.Model):
    etitle = models.CharField(max_length=10)
    etext = models.CharField(max_length=50)
    ecount = models.IntegerField(default=0)
    eauthor = models.ForeignKey(Author)

App/views.py
from random import random

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App.models import *





def homeBlog(request):
    titles = Blog.objects.all()
    context = {'titles': titles}
    return render(request, 'myblog.html', context)




def homeContent(request,btitle):
    b = Blog.objects.filter(btitle=btitle)[0]
    b.bcount += 1
    b.save()
    contents = Content.objects.filter(ctitle__btitle__contains='%s'%btitle)
    context = {'contents':contents, 'btitle':btitle,'b':btitle}
    return render(request,'blogpage.html',context)


def addBlog(request):
    b = Content()
    b.btitle = '标题2'
    b.bname = '作者2'
    b.bcount =0
    b.save()
    return HttpResponse('添加成功')

def addContent(request):
    c = Content()
    g = Blog.objects.last()
    c.ctitle = g
    c.cname = '作者2'
    c.cinfo = 'MVC即模型－视图－控制器模式，就是为那些需要为同样的数据提供多个视图的应用程序而设计的。它很好地实现了数据层与表示层的分离，特别适用于开发与用户图形界面有关的应用程序。控制器用来处理用户命令以及程序事件；模型维护数据并提供数据访问方法；视图用于数据的显示。'
    c.save()
    return HttpResponse('添加成功')


#----------------------------------
def index(request):
    eassy = Eassy.objects.all()
    context = {'eassy':eassy}
    return render(request,'index.html',context)

def detail(request, title):
    eassy = Eassy.objects.filter(etitle=title)[0]
    eassy.ecount += 1
    eassy.save()
    context = {'eassy': eassy}
    return render(request, 'detail.html', context)

App/templates/blogpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>myblog</title>
</head>
<body>
    {% for content in contents %}
        <h1>{{ content.ctitle.btitle }}</h1>
        <p>作者：{{ content.cname }}</p>
        <b>内容：</b><br/>
        <p>{{ content.cinfo }}</p>
    {% endfor %}

    <div>

    </div>
</body>
</html>

App/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        
    </style>
</head>
<body>
    <table border="1px">
        <tr>
            <td>标题</td>
            <td>作者</td>
            <td>内容</td>
        </tr>

            <tr>
            <td>{{ eassy.etitle }}</td>
            <td>{{ eassy.eauthor.aname }}</td>
            <td>{{ eassy.etext }}</td>
            </tr>


{#        {% for e in eassy %}#}
{#            <tr>#}
{#                <td>{{ e.etitle }}</td>#}
{#                <td>{{ e.eauthor.aname }}</td>#}
{#                <td>{{ e.etext }}</td>#}
{#            </tr>#}
{##}
{#        {% endfor %}#}

    </table>

</body>
</html>

App/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>
<table border="1px">
    <tr>
        <th>标题</th>
        <th>作者</th>
        <th>次数</th>
    </tr>


    {% for eassy in eassy %}
    <tr>
        <td><a href="{% url 'blog:detail' eassy.etitle %}">{{ eassy.etitle }}</a></td>
        <td>{{ eassy.eauthor.aname }}</td>
        <td>{{ eassy.ecount}}</td>
    </tr>
    {% endfor %}



</table>





</body>
</html>

App/templates/myblog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>myblog</title>
    <style>
       tr td{
            text-align: center;
       }
        h1{
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>myblog</h1>
    <table width="600">
        <tr>
            <th>标题</th>
            <th>作者</th>
            <th>访问次数</th>
        </tr>

        {% for title in titles %}
            <tr>
            <td><a href={% url 'blog:homecontent' title.btitle %}>{{ title.btitle }}</a></td>
            <td>{{ title.bname }}</td>
            <td>{{ title.bcount }}</td>
            </tr>
        {% endfor %}

    </table>

</body>
</html>